spring:
    application:
        name: gateway-server

server:
  port: 9004
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9102/eureka 

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: microservice-produits
        uri: lb://microservice-produits
        predicates:
        - Path=/microservice-produits/**
      - id: microservice-paiement
        uri: lb://microservice-paiement
        predicates:
        - Path=/microservice-paiement/**
      - id: microservice-commandes
        uri: lb://microservice-commandes
        predicates:
        - Path=/microservice-commandes/**





#spring.application.name=gateway-server
#server.port=9004

#Eureka
#eureka.client.serviceUrl.defaultZone: http://localhost:9102/eureka/

# use netflix eureka discovery service
#spring.cloud.gateway.discovery.locator.enabled=true 
#spring.cloud.gateway.routes.id=microservice-produits
#spring.cloud.gateway.routes.uri=lb://microservice-produits # netflix eureka correspondent service
#spring.cloud.gateway.routes.predicates.Path=/microservice-produits/**
# how we will map the url to the target service